---
# tasks file for frontend_servers
  - name: Install packages
    package:
      name: "{{ packages }}"
      state: latest

  - name: Enable Services
    service:
      name: "{{ item }}"
      enabled: yes
    loop: "{{ services }}"

  - name: Place haproxy config file
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: Restart Services